#!/bin/bash
echo 
echo Hello, ${USER}, \(we are here.\)
echo '${PWD}='${PWD} 
echo '$(tty)='$(tty)

echo 
sed_test="echo 'abcd123 cxv678' |tee /dev/tty | sed 's/\([a-z]*\).* \([a-z]*\).*/\1xx \1yy/'"
echo ${sed_test}
eval "$sed_test"

echo 
echo $(ls)
